# Generated by Django 2.2.12 on 2020-08-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True, help_text='Ссылка на сайт'),
        ),
    ]
