# Generated by Django 2.2.17 on 2020-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_formfield_clean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
