# Generated by Django 2.2.17 on 2020-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammember_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name_plural': 'Команда проекта'},
        ),
    ]
