# Generated by Django 2.2.17 on 2020-12-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20201202_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tg',
            field=models.URLField(blank=True, help_text='URL telegram'),
        ),
    ]
