# Generated by Django 2.2.12 on 2020-05-02 10:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200502_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='form_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'breed': 'collie'}),
            preserve_default=False,
        ),
    ]
