# Generated by Django 2.2.12 on 2020-05-10 07:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200502_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.core.fields.StreamField([('emphasize', wagtail.core.blocks.CharBlock(icon='title', label='Выделить текст', template='blocks/event_emphasize_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Текст', template='blocks/event_paragraph_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Картинка справа', template='blocks/image_right_block.html')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Чистый HTML')), ('list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Пункт списка'), icon='list-ul', template='blocks/list_block.html')), ('blockquote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(label='Цитата')), ('author', wagtail.core.blocks.CharBlock(label='Автор'))], icon='openquote', template='blocks/quote_block.html')), ('form', wagtail.core.blocks.StreamBlock([('input', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('placeholder', wagtail.core.blocks.CharBlock(label='Подсказка', required=True)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Однострочное поле')), ('textarea', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('placeholder', wagtail.core.blocks.CharBlock(label='Подсказка', required=True)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Многострочное поле')), ('checkbox', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('choices', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Выбор'), required=False)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Чек-бокс поле')), ('select', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('choices', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Выбор'), required=False)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Выбор из списка')), ('emailfield', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('placeholder', wagtail.core.blocks.CharBlock(label='Подсказка', required=True)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Email')), ('numberfield', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название поля')), ('placeholder', wagtail.core.blocks.CharBlock(label='Подсказка', required=True)), ('required', wagtail.core.blocks.BooleanBlock(label='Обязательное поле', required=False))], label='Числовое поле'))], icon='form', template='blocks/event_form_block.html'))]),
        ),
    ]
