# Generated by Django 2.2.12 on 2020-08-22 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20200822_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='form_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
