# Generated by Django 2.2.13 on 2020-09-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customhtmlpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customhtmlpage',
            old_name='page_tamplate',
            new_name='page_template',
        ),
    ]
