# Generated by Django 2.2.13 on 2020-09-10 11:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0003_auto_20200902_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderToHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Заголовок', max_length=90)),
                ('sub_title', models.CharField(help_text='Подзаголовок', max_length=90)),
                ('button_text_1', models.CharField(max_length=90)),
                ('button_href_1', models.URLField(blank=True)),
                ('button_text_2', models.CharField(max_length=90)),
                ('button_href_2', models.URLField(blank=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
