# Generated by Django 2.2.12 on 2020-05-11 01:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('shop', '0003_productpage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='name',
            field=models.CharField(blank=True, help_text='Название товара', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='option',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Название параметра')), ('cost', wagtail.core.blocks.FloatBlock(label='Стоимоть товара с параметром', required=False))], icon='openquote', label='Параметры товара', template='blocks/shop/option_block.html'))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductPageRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='shop.ProductPage')),
                ('shop_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
