# Generated by Django 2.2.12 on 2020-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productreview_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
