# Generated by Django 2.2.17 on 2020-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='dzen',
            field=models.URLField(blank=True, help_text='URL Yandex dzen'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='precious_plastic',
            field=models.URLField(blank=True, help_text='URL precious plastic'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='tg',
            field=models.URLField(blank=True, help_text='URL telegram'),
        ),
    ]
